version: "3.7"

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_DB: blogueira_de_baixa_renda
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
